on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: dependencies
      run: |
        sudo apt-get -y install git g++ imagemagick xclip libsdl1.2-dev libglu1-mesa-dev libgl1-mesa-dev
    - name: freetype
      run: |
        cd Tool-1/Build/freetype-2.13.2
        cd builds/unix
        chmod +x configure
        ./configure
        cd ../../
        make
        sudo make install
    - name: Clone Git Repositories
      run: |
        cd Tool-1/Build
        rm -rf OneLife/*
        rm -rf minorGems/*
        git clone https://github.com/is52hertz/YumWorldminorGems.git
        git clone https://github.com/is52hertz/YumWorld.git
        mv YumWorldminorGems/* minorGems
        mv YumWorld/* OneLife
        rm -rf YumWorld
        rm -rf YumWorldminorGems
    - name: Build Tool-1 [workflowBuildOneEditor]
      run: |
        cd Tool-1/Build
        cp OneLife/scripts/TestBuildLinux.sh .
        chmod +x TestBuildLinux.sh
        ./TestBuildLinux.sh
        find . -type f -name '*.o' -exec rm {} +
        find . -type f -name '*.dep' -exec rm {} +
        rm OneLife/gameSource/Makefile.minorGems_dependencies
        cd OneLife/gameSource
        ./makeEditor.sh

    - name: Copy EditOneLife
      run: |
        cp Tool-1/Build/OneLife/gameSource/EditOneLife Tool-1/

    - name: Display Build Result
      run: |
        ls -l Tool-1/Build/OneLife/gameSource/EditOneLife
    - name: Upload Build Result
      uses: actions/upload-artifact@v2
      with:
        name: EditOneLife[Tool-1]
        path: Tool-1/Build/EditOneLife
      

